name: Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  coverage:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go:
          - "1.19"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      # change to coverage.out after https://github.com/PowerShell/PowerShell/issues/6291
      - name: Calc coverage
        run: |
          go test -v -covermode=count -coverprofile=coverageout ./...

      - name: Convert coverageout to coveragelcov
        run: |
          go install github.com/jandelgado/gcov2lcov@latest
          gcov2lcov -infile=coverageout -outfile=coveragelcov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coveragelcov
          parallel: true

  coverage_finalize:
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - name: Coveralls finalization
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
